### ISSUE TITLE
配達エリアについて

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#100]
現在、マップ状ですが、
それいがいに、

都道府県・市町村で配達エリアを決められるようにもしたいです。

また、マップ状で入ったところの都道府県・市町村が、文字で出て、自分の購入者が自分のエリアが購入エリアかがわかるようにシて下さい。

**Comment by take-iwa** [comment]
@alexeypolitov 今の所、サービスの配達エリアは購入者側からは分かりません。
#124 でも書きましたが、サービス詳細に配達エリアの表示が必要だと思います。

あと、宮本さんが書いてるこの部分↓も対応できれば、お願いします。

> また、マップ状で入ったところの都道府県・市町村が、文字で出て、自分の購入者が自分のエリアが購入エリアかがわかるようにシて下さい。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。

**Comment by take-iwa** [comment]
配達範囲表示確認しました。文字は出さなくても見た目でわかりやすいので、これでOKだと思います。
