### ISSUE TITLE
評価の星マークの桁数

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#117]
表示される数字は、小数点第１位まで
下の場合、「4.3」
<img width="365" alt="2017-06-08 15 00 22" src="https://user-images.githubusercontent.com/23730555/26918128-a71ef3f0-4c6b-11e7-85f5-1c77b7b94dbc.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境で確認しました。OKです。
