### ISSUE TITLE
サービス・商品の個数設定と数量限定が保存されない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#118]
入力して保存しても次に開くと０に戻ってしまう。
そのためか購入者側で注文するときに数量に上限がない。
<img width="730" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/26918306-66b957a0-4c6c-11e7-9016-e4c7c525a251.png">

**Comment by take-iwa** [comment]
できれば、値段設定の部分は↓のような順にできるといい
〇〇円　　/ 　　数量　　単位

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境で確認しました。

できれば、値段と数量の間に”/”スラッシュが欲しいところです。
料金のイメージとして　”200円／2 個” 　＝　「2個で200円」という表示がわかりやすいと思いますので。

**Comment by alexeypolitov** [comment]
@take-iwa  修正しました

**Comment by take-iwa** [comment]
@alexeypolitov #96でも書いたようにサービス内容を保存した時に「ネットワークに接続できません」と出るせいか、単位となる数量を保存できず、何を設定しても１になります。確認お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
