### ISSUE TITLE
料金計算について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#119]
消費税率が１０％になっているので、８％に修正。
また、税金を計算する場合は、
（商品代金＋送料）x  税率
で計算してください。
また、発送予定時間の時間帯設定を日本時間にしてください。
加えて、文言変更「文句を言います」→「苦情報告」
![_2017-06-08_12_01_19](https://user-images.githubusercontent.com/23730555/26918464-1a011500-4c6d-11e7-88cc-d24602ec50e0.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境で確認しました。
税率設定と「苦情報告」はOKです。

タイムゾーンについては、本番に移すときには必ずお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa  修正しました。過去の注文が変わらないですので新しい注文でご確認下さい

**Comment by take-iwa** [comment]
確認しました。
