### ISSUE TITLE
単位について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#120]
この二つでお願いします。

個
時間

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境でOKでした。

**Comment by take-iwa** [comment]
本番にて確認しました。
すみません。よく考えたら、数量として小数点以下を登録できないので、時間の単位として「分」も追加してください。

**Comment by take-iwa** [comment]
管理画面で追加できるんでした。OKです。
