### ISSUE TITLE
注文ステータスの日本語化

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#121]
New arrival order
新規注文

Confirmed
受注確認済み

Preparing
準備中

Delivery
配達中

Delivered
配達済み

Canceled by seller
受注辞退

Canceled by buyer
注文キャンセル

Canceled by admin
強制キャンセル

In revision
改訂中

Closed
完了

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境で確認できました！

**Comment by take-iwa** [comment]
okです。
