### ISSUE TITLE
換金後の「問題？」ボタンのリンク

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#122]
今の所、リンクなし。
お問い合わせフォームに飛ぶようにする

**Comment by take-iwa** [comment]
@alexeypolitov 売上レポート・出入金の「問題？」ボタンからのリンク確認しました。

ただ、ユーザーメニューのお知らせの画面にも換金後の「問題？」ボタンがあり、リンクがありません。こちらもお問い合わせフォームへ飛ぶようお願いします。
<img width="976" alt="2017-08-17 22 14 39" src="https://user-images.githubusercontent.com/23730555/29414125-b46e1468-8399-11e7-9c68-4d361e2d9f7e.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。新しいお知らせでご確認ください
