### ISSUE TITLE
商品・サービスの詳細画面の表示項目

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#124]
以下の３つを追加で表示する
・限定数量
・配達エリア
・配達方法

価格の部分は、数量と単位を追加
「〇〇円 / 数量 単位」
![_2017-06-08_18_12_31](https://user-images.githubusercontent.com/23730555/26956784-6318482e-4cfb-11e7-97a8-0cb911c49864.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境で確認しました。

限定数量と配達方法＋配達エリア　完璧です。

<img width="178" alt="2017-08-08 13 45 32" src="https://user-images.githubusercontent.com/23730555/29057011-289ec9c2-7c42-11e7-8868-0a345a1ffa60.png">
こちらは、”数量”　”単位”は消して
　200円 / 1個
となるようにお願いいたします。

**Comment by alexeypolitov** [comment]
@take-iwa  修正しました

**Comment by take-iwa** [comment]
「〇〇個　XXX円」

ここですが、括弧「」は必要ないので、消してください。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
