### ISSUE TITLE
サービスの公開/非公開設定

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#131]
ボタンの表示を逆にして、現在公開なのか非公開なのかを表示させてください。
<img width="271" alt="_2017-08-17_22_38_03" src="https://user-images.githubusercontent.com/23730555/29415124-e6e038c4-839c-11e7-89a4-bc2c3c75b738.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 文字は逆になっていますが、色も逆でお願いします。
公開で青、非公開でグレー

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
