### ISSUE TITLE
問い合わせを送るボタン

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#133]
「公開する」
　↓
送信する

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 一般問い合わせはOKですが、換金の'問題?'から開く問い合わせページも修正してください。
<img width="485" alt="2017-09-11 12 58 27" src="https://user-images.githubusercontent.com/23730555/30258030-f74a88a6-96f0-11e7-9008-8ca18bee7a1c.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
