### ISSUE TITLE
注文の支払い方法

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#136]
Card：クレジットカード払い
Bank Account：？？？？
Cash：直接現金払い

"Bank Account"は、何払いになりますか？
銀行振込なら、口座情報は必要なんでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa そうです。銀行振込です。何を追加すればいいですか？

**Comment by take-iwa** [comment]
@alexeypolitov 注文時に銀行振込を選択すると、口座情報の入力を求められます。
買う側なのに口座情報の入力は必要ですか？

買う側に必要なのは、振込金額・振込先の情報を与えることではないかと。
<img width="811" alt="2017-09-11 13 20 59" src="https://user-images.githubusercontent.com/23730555/30258405-189c1134-96f4-11e7-90cd-59f3bca1e722.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 銀行振込で注文した際、受注者側に注文データが来ません。確認お願いできますか？

**Comment by alexeypolitov** [comment]
@take-iwa 銀行振込なので、管理画面で「振込済み」にしないと表示されないです

**Comment by take-iwa** [comment]
@alexeypolitov そうでした・・失念しておりました。注文入ること確認しました。
ちなみに、発注者に対して振込先の情報はどのようにお知らせされますか？

**Comment by alexeypolitov** [comment]
@take-iwa メールが届くはずです。テンプレートありましたっけ？

**Comment by take-iwa** [comment]
@alexeypolitov すみません。メールテンプレート渡してないです。
準備いたします。

あと、すっかり忘れてましたが、
支払い方法の日本語化お願いします。

Card
Bank Account
Cash
↓
クレジットカード払い
銀行振込
直接現金払い

**Comment by alexeypolitov** [comment]
@take-iwa テンプレートください。すぐ直したいです

**Comment by alexeypolitov** [comment]
@take-iwa テンプレートください。すぐ直したいです

**Comment by take-iwa** [comment]
@alexeypolitov 
```
/* --- bank_account_info --- */
/* --- 【AIR MAID】ご注文のお支払いについてのご案内 --- */
<?php echo customer_name; ?>様

-----------------------------------
本メールはシステムにより自動で送信させて頂いております。
このままご返信いただいてもお答えできません。
お心当たりのない方は、メール本文のお問い合わせよりお知らせください。
-----------------------------------
こちらAIR MAID(エアメイド)カスタマーサポートです。
いつもAIR MAIDをご利用いただきまして、誠にありがとうございます。

お支払い方法を銀行振込でご注文いただきました下記の注文について、
ご請求額とお振込先の口座情報をご案内いたします。

尚、販売者へのお客様のご注文の通知は、お客様からのお振込を確認した後となります。
あらかじめ、ご了承ください。


■ご注文番号：<?php echo order_number; ?>

■お支払い金額について
　サービス・商品：<?php echo ; ?>
　送料：<?php echo ; ?>
　消費税：<?php echo ; ?>
　——————
　ご請求金額合計：<?php echo ; ?>


■お振込先口座情報
<?php echo bank_info ;?>


ご質問等ございましたら、
下記のAIR MAIDカスタマーサポートのメールアドレスまたはお問い合わせフォームよりお送りください。

今後ともAIR MAIDをよろしくお願いいたします。

===================================
人と人とをつなぐAIR MAID(エアメイド)
　https://airmaid.jp/
AIR MAID(エアメイド) カスタマーサポート
　お問い合わせ：info@airmaid.jp
===================================
presented by 丸井織物株式会社

```

**Comment by take-iwa** [comment]
@alexeypolitov 料金の変数名はわからなかったので、入っていません。どうぞよしなに。

**Comment by alexeypolitov** [comment]
@take-iwa 
> Card
> Bank Account
> Cash
> ↓
> クレジットカード払い
> 銀行振込
> 直接現金払い

修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 日本語化、支払い関係のメール確認しました。
