### ISSUE TITLE
有料掲載の支払い画面　日本語化

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#137]
左サイドメニュー
Publish after pay

支払い後、すぐ公開する

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 余計な文言入ってます。

支払い後、すぐ公開する- 2営業日以内で振り込むとなりますs - 2営業日以内にご指定の口座へ振り込まれます。

↓
支払い後、すぐ公開する

<img width="233" alt="2017-09-11 13 02 43" src="https://user-images.githubusercontent.com/23730555/30258133-c68e78f2-96f1-11e7-9310-c297b09c05cc.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
