### ISSUE TITLE
売上レポート・出入金の文言修正

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#139]
１）3,381円換を振り込みました
　　　↓
　　3,3,81円を引き出しました
<img width="291" alt="2017-09-08 8 17 39" src="https://user-images.githubusercontent.com/23730555/30189486-10528e04-946f-11e7-81ab-f3e85806bd25.png">

２）引き出し申請ページで
　2営業日以内で振り込むとなりますs
　　↓
　2営業日以内にご指定の口座へ振り込まれます。
<img width="324" alt="2017-09-08 8 24 52" src="https://user-images.githubusercontent.com/23730555/30189551-993a06de-946f-11e7-8d54-bfdc0e6c55dd.png">

３）支払い方法のとこ
　Bank Account
　　↓
　銀行振込

**Comment by alexeypolitov** [comment]
@take-iwa 
1. どういう意味ですか？

**Comment by alexeypolitov** [comment]
@take-iwa 1以外修正しました。ご確認ください。

**Comment by take-iwa** [comment]
![Uploading スクリーンショット 2017-09-11 13.07.27.png…]()

**Comment by take-iwa** [comment]
@alexeypolitov すみません。１番は大岩のコメントがミスってますね。
正しくは、こうです。

１）3,381円換を振り込みました
　　　↓
　　3,381円を引き出しました

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
