### ISSUE TITLE
支払い関係のメール内容について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#146]
クレジットカード払いのメール

<img width="210" alt="_ _yahoo_ 34" src="https://user-images.githubusercontent.com/23730555/30327395-d743b02a-9806-11e7-9453-5b6189458886.png">

**Comment by take-iwa** [comment]
他のメールに関しても、合計の小数点以下は不要ですので、整数値でお願いします。

**Comment by take-iwa** [comment]
現金払いのメール

<img width="234" alt="_ _yahoo_ 37" src="https://user-images.githubusercontent.com/23730555/30328153-7a08e51c-9809-11e7-98b9-9085975170fe.png">

**Comment by take-iwa** [comment]
銀行振込のメール

<img width="210" alt="_ _yahoo_ 41" src="https://user-images.githubusercontent.com/23730555/30328352-0ab814a2-980a-11e7-8f94-deade6dbbd80.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 
クレジットカード払いOK
現金払いOK
銀行振込NG  // 値段がないです
<img width="206" alt="_ _yahoo_ 44" src="https://user-images.githubusercontent.com/23730555/30331548-15dd0ed8-9813-11e7-82dd-705f50c54f27.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
