### ISSUE TITLE
有料掲載期間終了お知らせメール

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#148]
文字のところまでリンクになっています。

<img width="336" alt="air_maid _-_h_ooiwa7701_gmail_com_-_gmail" src="https://user-images.githubusercontent.com/23730555/30628394-12d2204e-9e11-11e7-9faa-1a08ff48fbd6.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
確認いたしました！
<img width="252" alt="_ _google 944" src="https://user-images.githubusercontent.com/23730555/30639803-55b56afe-9e3b-11e7-9c1f-d1d3bbcff146.png">
