### ISSUE TITLE
お届け先が配達エリア外でも注文できてしまう

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#149]
注文者のお届け先が
提供者が設定した配達エリア外にもかかわらず、注文できてしまう。

例）配達エリア：東京
　　お届け先：石川

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov こちらまだお届け先が石川なのに配達エリアが東京圏内のサービスの注文までできました。
確認していただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov エリア東京のサービスがお届け先大阪で変えてしまいました。確認お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa すみません、バグでしたもう一回ご確認していただけますか？
