### ISSUE TITLE
サービス登録の時間設定

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#150]
確認した感じ、0時を跨いだ設定にすると、どこが注文できる時間帯かがわからない。

22:00~02:00となっていた時に23:00で設定できない。
他の時間帯もエラーになって注文できない

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 営業時間設定で0時をまたぐ設定できないので、新規に追加されるサービスについては大丈夫そうです。
すでに日をまたいで設定してあるサービスは、どうやって入れたのでしょう？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
