### ISSUE TITLE
限定数量について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#151]
限定数量が０の場合、「限定数量なし」と表示する。

設定のところに
```
数量を限定しない場合は、「０」を設定してください。
```
と記載お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 表示の修正確認できませんでした。

<img width="483" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30728687-b182937a-9f94-11e7-8412-9b80dfb2e593.png">

<img width="471" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30728721-fe780e1c-9f94-11e7-9e0e-bd69f161d326.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
