### ISSUE TITLE
お届け先設定について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#153]
お届け先タイトル
↓
お届け先登録名

番地・建物名　　と　　電話番号　　は、行を変える
```
番地・建物名
番地
```

<img width="419" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30638948-16bbe768-9e38-11e7-9073-7769bbcf4034.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 変わっていないようです。確認お願いします。

<img width="470" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30728752-3edb2534-9f95-11e7-93bd-8bf7f81ac4ef.png">
