### ISSUE TITLE
注文ステータスについて

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#154]
受注者が「配達済み」にした時、
注文者に対して、
ステータス変更通知とともに、受渡しが完了した後、注文ステータスを「完了」に変えてもらうように催促するメールを送る。
もし、一週間経っても「配達済み」から「完了」にならなかった場合、強制的に「完了」に変更する。
その旨を伝えた上で、問題があった場合は一週間以内に苦情報告するように依頼する。

一週間経って強制完了する場合は、強制的に完了したことがわかるような表示にする。

**Comment by take-iwa** [comment]
[airmaid_mail_text0921.txt](https://github.com/DecodeLLC/cookle-web/files/1319691/airmaid_mail_text0921.txt)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 確認お願いします。
<img width="193" alt="_ _yahoo_ 61" src="https://user-images.githubusercontent.com/23730555/30728874-344e5a2c-9f96-11e7-8e86-8a08274661bb.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov メールの内容はOKです。
すみません。メールの件名だけ差し替えお願いします・・・。申し訳ないです。

【AIR MAID】ご注文の進捗状況のお知らせと受け渡し完了報告のお願い
　　　↓
【AIR MAID】ご注文の進捗と受け渡し完了報告依頼について

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
