### ISSUE TITLE
スマホ表示の場合、カートがどこにあるかわかりづらい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#155]
カートに入れた時も、そこからカート画面に行けるかわかりづらい、
カートはtopのメニューに並べておく

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov かわってないように見えますが。確認お願いします。

<img width="225" alt="img_0042_png" src="https://user-images.githubusercontent.com/23730555/30728923-96ba1232-9f96-11e7-85f3-9e6dc8011a20.png">
