### ISSUE TITLE
メッセージやお知らせが来た時にもっとアイコンを目立つように

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#156]
現在、色が変わるだけですが、「！」マークを入れるなどして、通知に気付きやすくする

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov かわっていないように見えます。確認お願いします。

<img width="169" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30728950-e197b21e-9f96-11e7-94f2-a70394ed9d6b.png">

**Comment by take-iwa** [comment]
確認できました。

<img width="112" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30736835-4d4dbfc6-9fbf-11e7-9601-758098f92321.png">
