### ISSUE TITLE
特定商取引法のページを追加

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-web#157]
管理画面には、特定商取引法の項目あるが開かない。
ユーザー側では、フッターに追加

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 確認お願いいたします。

<img width="523" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30729018-50aa6016-9f97-11e7-806a-f73d344956b1.png">

**Comment by take-iwa** [comment]
@alexeypolitov フッターの文言修正　と　情報ページのサイドメニューにも追加

<img width="191" alt="banners_and_alerts_ _airmaid" src="https://user-images.githubusercontent.com/23730555/30737175-a5d29738-9fc0-11e7-983b-dfd63a808b03.png">

<img width="119" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30737235-db838e64-9fc0-11e7-8bea-7b85b33ee9f1.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
