### ISSUE TITLE
メッセージ機能

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#24]
購入前・購入後のメッセージ問い合わせ機能

**Comment by take-iwa** [comment]
直接メッセージ機能確認しました。

以下の機能は、なしになったんですか？
> ＋添付ファイルも可能にしてください。
> 
> さらに、禁止メッセージ登録機能もお願い致します。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。

**Comment by take-iwa** [comment]
@alexeypolitov 添付ファイルで.png、.txtは問題なく見られました。
他にありそうな.jpg、.pdfを試しましたが、これらは読み込めないフォーマットとして開けなかったです。
また、.csvも試しましたが、ファイルの内容が以下のようなawsのS3のURLになってました。
> https://s3-ap-northeast-1.amazonaws.com/storage.airmaid.jp/files/59957a08-b358-4ae3-a086-791aac1f1725.csv

確認お願いいたします。

**Comment by alexeypolitov** [comment]
@take-iwa 対応必要なフォーマットをアップしていただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 確認できているところで、.jpg, .pdf, .csvの対応をお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa .jpg, .pdf, .csvは未対応ですね？あと全体的にどのフォーマットは必要なのかまとめていただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 
■画像はメッセージ画面で見たい
*.gif, *.jpg, *.jpeg, *.png
■あとは、ダウンロードできればOK
*.pdf, *.txt

とりあえず、これで大丈夫だとお思います。.csvは不要で。

**Comment by alexeypolitov** [comment]
@take-iwa 対応しました。ご確認ください
