### ISSUE TITLE
新規登録後にサンクスメールが飛ばない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#42]
新規登録後にサンクスメールが飛ばない

**Comment by take-iwa** [comment]
@alexeypolitov こちら、確かに現在もメール来ないのですが、追加していただけますか？

**Comment by alexeypolitov** [comment]
@take-iwa メールの内容ください

**Comment by take-iwa** [comment]
@alexeypolitov お願いします。
[airmaid_thanks_mail.txt](https://github.com/DecodeLLC/cookle-web/files/1247829/airmaid_thanks_mail.txt)

**Comment by take-iwa** [comment]
@alexeypolitov お願いします。
[airmaid_thanks_mail.txt](https://github.com/DecodeLLC/cookle-web/files/1247829/airmaid_thanks_mail.txt)

**Comment by alexeypolitov** [comment]
@take-iwa 対応しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 届きました。メールの件名だけ修正お願いします。
共有依頼【Airmaid】
　　　↓
【AIR MAID】ご登録完了のお知らせ

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
