### ISSUE TITLE
プロフィールに必要な項目

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#44]
画像
名前
ニックネーム（普段はニックネームが出るように）
メールアドレス：
年齢（選択式）１０代～８０代まで
性別（選択式）男性・女性
住所：◯◯都道府県◯◯区市まで（公開非公開可能）
自己紹介：（内容）と一緒

**Comment by take-iwa** [comment]
@alexeypolitov 住所の表示は、なしになったのですか？

**Comment by alexeypolitov** [comment]
@take-iwa なってないはずです。問題があるところをスクリーンショットでいただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov プロフィール編集画面ですよね？住所の欄はないです。

![airmaid_profile](https://user-images.githubusercontent.com/23730555/29070129-d52243f0-7c78-11e7-9469-0837b4b3591c.png)

**Comment by take-iwa** [comment]
お届け先や配達エリアを設定するため、改めてプロフィールに入力する必要なしです。
他はOKです。
