### ISSUE TITLE
パスワードを忘れた方へのサブタイトル文章

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#91]
http://airmaid.decodeapps.io/#/forgot

パスワードを忘れた方こちらへ

パスワードを忘れた方はこちらから、登録したメールアドレスを入れて下さい。
その後、メールにてコードが届きますので、コードを入れてパスワードを再設定して下さい。

**Comment by take-iwa** [comment]
修正確認しました。
