### ISSUE TITLE
パスワード忘れメール文章

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#92]
タイトル：AirMaidパスワード再設定コード

◯◯様

パスワードの再設定のコードをお送りします

◯◯◯◯◯

下記URLより、コードを入力して再設定をしてください。

http://xxxxx.com(コードのところのURL）

=========================================-
個人をつなぐAirMaid
丸井織物株式会社
03-6447-4321
info@airmaid.jp
=========================================

**Comment by take-iwa** [comment]
@alexeypolitov パスワード忘れのメールが飛んできません。本番環境でチェックしてます。

**Comment by take-iwa** [comment]
@alexeypolitov h.ooiwa7701@gmail.comに21時ごろに再設定メール送ったのですが、届かないです。
確認お願いします。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認ください。メールは迷惑に入る可能性があります

**Comment by take-iwa** [comment]
@alexeypolitov 届きました。本文少し修正お願いします。
<img width="1011" alt="2017-08-31 2 03 03" src="https://user-images.githubusercontent.com/23730555/30011671-2723e554-9174-11e7-8aa1-89f3350b1c73.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 確認しましたが、直っていないようです。再度、確認していいただけますか？
１）タイトル：AirMaidパスワード再設定コード 　←　削除
２）パスワードが目立つように、パスワードの後に改行

<img width="491" alt="2017-09-06 8 37 07" src="https://user-images.githubusercontent.com/23730555/30087965-b07f7a00-92de-11e7-9357-2729d7dbf11d.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 直ってます？
<img width="500" alt="2017-09-11 12 52 27" src="https://user-images.githubusercontent.com/23730555/30257944-5ac62a08-96f0-11e7-8dba-295e56c7e000.png">

**Comment by alexeypolitov** [comment]
@take-iwa もう一回ご確認していただけますか？
