### ISSUE TITLE
英語を日本語にuntill

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#93]
http://airmaid.decodeapps.io/#/profile/service/

tell about dish
内容についてできるだけ詳しくお書き下さい。

DeliveryZone
配達地域

BusinessDay
営業曜日

banner type
出稿タイプ

無料販売
有料販売（有料型は検索上位になりPVが大幅にアップします

1 month
1 week

１ヶ月
１週間

**Comment by take-iwa** [comment]
@alexeypolitov すみません。こちらの指示ミスになりますが、

"有料販売（有料型は検索上位になりPVが大幅にアップします"

の閉じカッコを足してください。
　　　　　　　　　　　　　　　　　　　　　　　　　　　  ↓
"有料販売（有料型は検索上位になりPVが大幅にアップします）"

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました
