### ISSUE TITLE
サービスを追加の文字変更

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#94]
http://airmaid.decodeapps.io/#/profile/orders/1

サービス・商品を追加して販売

**Comment by take-iwa** [comment]
@tomoyuki1110 @alexeypolitov 

サービス・商品を追加

でどうでしょうか？

**Comment by tomoyuki1110** [comment]
それでよいです。

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました

**Comment by take-iwa** [comment]
@alexeypolitov トップのページのボタンは変わっていますが、ユーザー画面のボタン文言が「サービスを追加」のままです。確認お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
