### ISSUE TITLE
サーバ上の言語を全部日本語に

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#96]
例えば右上のこの画像
![2017-04-12 20 25 46](https://cloud.githubusercontent.com/assets/17405609/24955410/489e4c38-1fbe-11e7-9dd7-ca12ca2f3764.png)

Please add business days otherwise~~~

営業日をご記載下さい。
営業の記載なくサービス・商品の販売は出来ませんのでご了承下さい。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境ですが、以下のもの見かけました。本番ではすべて日本語？
<img width="358" alt="2017-08-08 15 08 44" src="https://user-images.githubusercontent.com/23730555/29069831-8870262c-7c77-11e7-98d5-f3bf210d15af.png">
<img width="335" alt="2017-08-08 15 11 51" src="https://user-images.githubusercontent.com/23730555/29069834-897f3a08-7c77-11e7-807e-2fcfbc437e7d.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。

**Comment by take-iwa** [comment]
@alexeypolitov 日本語になっているのは確認しましたが、サービスの内容を変更して「保存」した時と　有料掲載のための「支払いへ」を押した時に以下が出ます。
確認お願いします。
<img width="322" alt="2017-08-17 21 32 36" src="https://user-images.githubusercontent.com/23730555/29412452-dbe5fbf6-8393-11e7-9372-9fb0ed8059d9.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
