### ISSUE TITLE
日本語変更

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/cookle-web#97]
http://airmaid.decodeapps.io/#/profile/edit?action=address

郵便局国を入れて下さい

ではなく郵便番号を入れて下さい。住所が自動で検索されます。
に変更

**Comment by take-iwa** [comment]
@alexeypolitov 本番環境で見ました。
「住所が自動で検索されます」の文言はないですが、OKだと思います。

同じページの日本語化をもう一つお願いします。
ページトップに
「Right click to add new address」
とあるので、これも
「届けて欲しい場所をマップ上で右クリックすると、新しいお届け先として登録できます。」
に修正してください。

それと日本語化ではありませんが、マップから住所を取得した時、フォームに合わない感じで入力されるので、修正してください。
<img width="828" alt="2017-08-08 14 40 27" src="https://user-images.githubusercontent.com/23730555/29057784-bbd7ae34-7c47-11e7-9993-22b30895f1cb.png">

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。

**Comment by take-iwa** [comment]
確認しました。OKです。
